module: LeBonCoin
author: JeanSarda
author_url: 'https://jeansarda.com'
copyright: '© 2020 [Jean Sarda](https://jeansarda.com)'
min_acl: private
theme: apple
swift_version: 5.3
xcodebuild_arguments:
    - '-project'
    - LeBonCoin.xcodeproj
    - '-scheme'
    - LeBonCoin
documentation: docs/Markdown/*.md
output: docs/swift
module_version: 1
custom_categories:
  - name: Guides
    children:
    - Documentation
  - name: Views
    children:
    - ListingTableViewCell
  - name: Models
    children:
    - Listing
    - ListingViewModel
    - Images
    - Category
  - name: Navigation Module
    children:
    - NavigationViewController
    - NavigationInteractor
    - NavigationPresenter
    - NavigationRouter
    - NavigationPresenterToViewProtocol
    - NavigationInteractorToPresenterProtocol
    - NavigationPresenterToInteractorProtocol
    - NavigationViewToPresenterProtocol
    - NavigationPresenterToRouterProtocol
    - NavigationStrings
  - name: List Module
    children:
    - ListViewController
    - ListInteractor
    - ListPresenter
    - ListRouter
    - ListPresenterToViewProtocol
    - ListInteractorToPresenterProtocol
    - ListPresenterToInteractorProtocol
    - ListViewToPresenterProtocol
    - ListPresenterToRouterProtocol
    - ListStrings
  - name: Detail Module
    children:
    - DetailViewController
    - DetailInteractor
    - DetailPresenter
    - DetailRouter
    - DetailPresenterToViewProtocol
    - DetailInteractorToPresenterProtocol
    - DetailPresenterToInteractorProtocol
    - DetailViewToPresenterProtocol
    - DetailPresenterToRouterProtocol
    - DetailStrings
  - name: Custom Views
    children: 
    - CategoryView
    - FilterButton
    - FilterButtonDelegate
  - name: Entry Points
    children: 
    - AppDelegate
    - SceneDelegate
  - name: Network
    children:
    - Routes
  - name: Helpers
    children:
    - LocalImageManager
    - LocalImageManagerError
    - URL
    - UIImageView 
    - NamedColors
    - DMSansFont
   
